name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ssh-agent (if necessary)
      run: sudo apt-get install openssh-client

    - name: Add SSH key to agent
      run: |
        echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy application
      run: |
        # Your deployment commands here
