name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run deployment script
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}  # Your SSH host
        username: ${{ secrets.USERNAME }}  # Your SSH username
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # The SSH private key secret
        port: 22
        timeout: 60s
        script: |
          docker pull ajuua/sampletest:latest
          docker ps -q -f "name=sampletest" | grep -q . && docker stop sampletest && docker rm sampletest
          docker run -d --name sampletest -p 8080:80 ajuua/sampletest:latest
        debug: true
