name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install SSH client and expect
      - name: Install SSH client and expect
        run: |
          # Install SSH client and expect
          sudo apt-get update -y && sudo apt-get install -y openssh-client expect

      # Step 3: Set up SSH key and passphrase
      - name: Set up SSH key and passphrase
        run: |
          # Setup SSH directory
          mkdir -p ~/.ssh
          
 
