name: Build and Deploy Angular App

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/angular-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SSH into the server and deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Pull the latest image from Docker Hub
          docker pull ${{ secrets.DOCKER_USERNAME }}/angular-app:latest
          
          # Stop the existing container if running
          docker ps -q -f "name=angular-app" | xargs -r docker stop

          # Remove the old container if it exists
          docker ps -a -q -f "name=angular-app" | xargs -r docker rm

          # Run the new container on port 8100
          docker run -d -p 8100:80 --name angular-app ${{ secrets.DOCKER_USERNAME }}/angular-app:latest
