name: SSH Connection Test

on:
  push:
    branches:
      - main

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up SSH
      run: |
        # Ensure the .ssh directory exists
        mkdir -p ~/.ssh

        # Save the private key to the id_rsa file
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa

        # Set proper permissions for the private key
        chmod 600 ~/.ssh/id_rsa

        # Start the SSH agent
        eval $(ssh-agent -s)

        # If a passphrase is provided, use it to add the key
        if [ -n "$SSH_PASSPHRASE" ]; then
          echo "$SSH_PASSPHRASE" | ssh-add ~/.ssh/id_rsa
        else
          ssh-add ~/.ssh/id_rsa
        fi

        # Disable strict host key checking (to avoid errors if the server's key is unknown)
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

        # Test SSH connection to the remote server
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$SERVER_IP 'echo "SSH connection successful"'

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
