name: Deploy Application

on:
  push:
    branches:
      - main  # Replace with your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Start SSH agent and add the private key
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Add GitHub to known_hosts (to prevent SSH host verification issues)
      - name: Add GitHub to known_hosts
        run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      # Step 4: Test SSH connection (Optional, ensures SSH works properly)
      - name: Test SSH connection
        run: ssh -T git@github.com

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-angular-app .

      # Step 6: Push Docker image to Docker Hub (Optional)
      # Uncomment if you're using Docker Hub for image storage
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push Docker image to Docker Hub
      #   run: |
      #     docker tag my-angular-app my-dockerhub-username/my-angular-app:latest
      #     docker push my-dockerhub-username/my-angular-app:latest

      # Step 7: Deploy to the server
      - name: Deploy to server
        run: |
          ssh ubuntu@your-server-ip << EOF
            docker stop angular-app || true
            docker rm angular-app || true
            docker pull my-angular-app:latest
            docker run -d --name angular-app -p 8100:8100 my-angular-app
          EOF

