name: Deploy with SSH Key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH and add the private key
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Start SSH agent and add the private key with passphrase
          eval $(ssh-agent -s)
          echo "$SSH_PASSPHRASE" | ssh-add ~/.ssh/id_rsa

          # Disable strict host key checking for the test
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H your-server-ip >> ~/.ssh/known_hosts

      # Test SSH connection
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@your-server-ip 'echo "SSH connection successful"'
        shell: /usr/bin/bash -e {0}
