name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install SSH client and set up SSH key
      - name: Install SSH client and set up SSH key
        run: |
          # Install SSH client if not already installed
          sudo apt-get update -y && sudo apt-get install -y openssh-client expect
          
          # Setup SSH directory and add private key
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Start SSH agent and add the private key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ls -l ~/.ssh

      # Step 3: Install expect to handle passphrase (if needed)
      - name: Install expect and add private key
        run: |
          # Use expect to add the private key (if passphrase required)
          expect << EOF
          spawn ssh-add ~/.ssh/id_rsa
          expect "Enter passphrase for ~/.ssh/id_rsa:"
          send "${{ secrets.SSH_PASSPHRASE }}\r"
          expect eof
          EOF

      # Step 4: Verify SSH connection to GitHub (Optional)
      - name: Verify SSH Connection
        run: ssh -o StrictHostKeyChecking=no -T git@github.com || echo "SSH connection failed"

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t yourdockerhubusername/my-app:latest .

      # Step 6: Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push yourdockerhubusername/my-app:latest

      # Step 7: Deploy Docker Image to Server and Run on Port 8100
      - name: Deploy Docker Image to Server
        run: |
          echo "Deploying Docker image to server..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@your-server-ip << 'EOF'
            docker pull yourdockerhubusername/my-app:latest
            docker run -d -p 8100:8100 yourdockerhubusername/my-app:latest
          EOF
