name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH to deploy the application
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the secret for the SSH private key

      # Deploy application to the server using SSH
      - name: Deploy to server
        run: |
          ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@64.227.159.217 << 'EOF'
            # Pull the latest Docker image from Docker Hub
            docker pull ajuua/sampletest:latest
            
            # Run the Docker container on port 8100
            docker run -d -p 8100:8100 --restart unless-stopped ajuua/sampletest:latest
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
