name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key stored in GitHub Secrets

    - name: Install SSH client (if necessary)
      run: sudo apt-get install -y openssh-client

    - name: Add SSH key to the agent
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY" | ssh-add -
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server's SSH host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H your-server-ip >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy application to server
      run: |
        # SSH into the server and run your deployment commands
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
          # Add your deployment steps here
          cd /path/to/your/app
          git pull origin main  # Or any other deployment steps
          docker-compose down   # Example, stop running containers
          docker-compose up -d  # Example, bring up containers
          # Additional commands can be added here
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
