name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Or your desired branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH key and passphrase
      - name: Set up SSH key and passphrase
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Start the SSH agent and add the private key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

          # Test SSH connection
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_HOST }} 'echo "SSH connection successful"'

      # Step 3: Build and deploy your application (add other steps here)
      # ...
