name: Docker Build and Push

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Checkout the repository to the runner

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for building multi-platform images

    - name: Login to Docker Hub
      uses: docker/login-action@v2  # Use Docker login action to authenticate to Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or token stored in GitHub Secrets

    - name: Build Docker Image
      run: |
        docker build -t ajuua/sampletest:tagname .  # Build the Docker image with your tag

    - name: Push Docker Image
      run: |
        docker push ajuua/sampletest:tagname  # Push the built Docker image to Docker Hub
