stages:
  - build
  - deploy

variables:
  SSH_USERNAME: "ubuntu" # Replace with your SSH username
  SSH_HOST: "143.110.251.96" # Replace with your SSH host
  SSH_PORT: "22" # Default SSH port
  DEPLOY_DIR: "/var/www/html/project" # Deployment directory
  SSH_KEY: $SSH_PRIVATE_KEY # Set in GitLab CI/CD variables

before_script:
  # Ensure SSH agent is running and private key is added
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

build:
  stage: build
  script:
    - echo "Building the application..."
    # Add build commands for your application (e.g., npm install, mvn package)
    - echo "Build process completed."

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - echo "SSH_USERNAME: ${SSH_USERNAME}"
    - echo "SSH_HOST: ${SSH_HOST}"
    - echo "Attempting SSH connection to ${SSH_USERNAME}@${SSH_HOST} on port ${SSH_PORT}"
    - ssh -v -i ~/.ssh/id_rsa "${SSH_USERNAME}@${SSH_HOST}" -p ${SSH_PORT} << EOF
        set -e
        echo "Connected to ${SSH_HOST}"
        mkdir -p ${DEPLOY_DIR}
        echo "Copying files to ${DEPLOY_DIR}"
        # Replace with commands to copy and deploy your application
        exit
      EOF
    - echo "Deployment completed successfully."
  only:
    - main # Change branch if necessary
