jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH with passphrase
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # GitHub secret containing private key

      # Set passphrase for SSH key
      - name: Set SSH Key Passphrase
        run: echo "${{ secrets.SSH_KEY_PASSPHRASE }}" | ssh-add -K ~/.ssh/id_rsa

      # Test SSH connection to the server
      - name: Test SSH connection
        run: |
          ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@64.227.159.217

      # Deploy the Docker container to the server
      - name: Deploy to server
        run: |
          ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@64.227.159.217 << 'EOF'
            # Pull the latest Docker image from Docker Hub
            docker pull ajuua/sampletest:latest
            
            # Stop and remove any existing container if it exists
            docker stop angular-app || true
            docker rm angular-app || true

            # Run the Docker container on port 8100
            docker run -d -p 8100:8100 --restart unless-stopped --name angular-app ajuua/sampletest:latest
          EOF
