name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on pushing to the `main` branch
  pull_request:
    branches:
      - main  # Trigger the pipeline on pull requests to `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Build Docker image
      run: |
        docker build -t your-image-name .
        docker tag your-image-name:latest your-dockerhub-username/your-image-name:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push your-dockerhub-username/your-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job will run after the `build` job completes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy Docker Compose file (if applicable)
      run: |
        scp -i ~/.ssh/id_rsa docker-compose.yml ubuntu@your-server-ip:/path/to/deployment/directory

    - name: Pull latest Docker image on server
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@your-server-ip << EOF
          cd /path/to/deployment/directory
          docker-compose pull
          docker-compose up -d
        EOF
