name: Deploy Docker Image to Server

on:
  push:
    branches:
      - main  # or specify the branch you want to trigger the pipeline on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ajuua/sampletest:latest .
        docker push ajuua/sampletest:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H 64.227.159.217 >> ~/.ssh/known_hosts  # Replace with your server IP
    
    - name: Deploy Docker container to server
      run: |
        ssh -i ~/.ssh/id_rsa root@64.227.159.217 << 'EOF'
          # Pull the latest Docker image from Docker Hub
          docker pull ajuua/sampletest:latest
          
          # Run the Docker container on port 8100
          docker run -d -p 8100:8100 --restart unless-stopped ajuua/sampletest:latest
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # The SSH private key in GitHub secrets
